- name: Unarchive pip rpm file /tmp
  unarchive: 
    src: pip.tar.gz
    dest: /tmp


- name: Install pip
  yum: 
      name="/tmp/pip/{{ item }}"
      state=present
      update_cache=yes
      allow_downgrade=yes
  with_items:
    - python2-pip-8.1.2-5.el7.noarch.rpm
    - python-backports-1.0-8.el7.x86_64.rpm
    - python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch.rpm
    - python-setuptools-0.9.8-4.el7.noarch.rpm



- name: remove the pip file
  file: path=/tmp/pip state=absent