


- name: Config sysctl
  template: 
    src: k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf
    mode: 0644
  tags:
    - sysctl


- name: load modprobe
  command: modprobe br_netfilter

- name: Sysctl apply
  shell: sysctl -p /etc/sysctl.d/k8s.conf

